openapi: 3.0.1
info:
  title: ChatGPT Plugin API
  version: 1.0.0
  description: A simple ChatGPT plugin that retrieves user information from the API.
servers:
  - url: https://try.hubcart.ai
paths:
  /user/:
    get:
      summary: Retrieve User Information
      description: Retrieves user information from the API.
      operationId: getUserInfo
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: User not found
        '500':
          description: Internal server error
components:
  schemas:
    UserResponse:
      type: string
      description: The user information.

