openapi: 3.0.0
info:
  title: ChatGPT Plugin API
  version: 1.0.0
paths:
  /user/:
    get:
      summary: Retrieve User Information
      description: |
        Retrieves user information from the API.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: User not found
        '500':
          description: Internal server error
